---
title: "Aluguel na cidade de São Paulo"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed 
runtime: shiny
---

```{r global, include=FALSE}

library(datasets)
library(shiny)
library(plotly)
library(leaflet)
library(tidyverse)
library(sf)
library(highcharter)
library(ggplot2)
library(ggrepel)
library(tidyverse)
library(scales)
library(knitr)
library(kableExtra)
library(xtable)
library(plyr)
library(DT)
library(readxl)

dados=as.data.frame(read_excel("data.cidade.xlsx", col_names=TRUE))

pizza.fun=function(dados,nomedistrito){
  novosdados1=dados[dados$district==nomedistrito,] 
    
  dadosprop=data.frame(N=table(novosdados1$type),
                       prop=as.numeric(round(100*table(novosdados1$type)/sum(table(novosdados1$type)),2)))
  dadosprop$N.Var1=as.character(dadosprop$N.Var1)
  
  dadosprop = dadosprop %>%
    arrange(desc(N.Var1)) %>% 
    mutate(pos = cumsum(prop) - prop/2)
  
  dadosprop$nome=paste(dadosprop$N.Var1,'(',dadosprop$prop,'%)',sep='')

  return(dadosprop)
}

bairroinfo.fun=function(dados,nomedistrito){
  novosdados=dados[dados$district==nomedistrito,] 
  
  tabelabairro=data.frame('Área'=as.character(round(mean(novosdados[,3]),1)),
                          'Quartos'=as.character(round(mean(novosdados[,4]),1)),
                          'Garagem'=as.character(round(mean(novosdados[,5]),1)),
                          'Aluguel (R$)'=as.character(round(mean(novosdados[,7]),0)),
                          'Custo Total (R$)'=as.character(round(mean(novosdados[,8]),0)))
  colnames(tabelabairro)=c('Área','Quartos', 'Garagem','Aluguel (R$)','Custo Total (R$)')
  return(tabelabairro)
}

todosbairrosinfo.fun=function(dados){
  tabelabairro=ddply(dados[,-c(1,6)],.(district),colwise(mean))
  colnames(tabelabairro)=c('Bairro','Área','Quartos', 'Garagem','Aluguel (R$)','Custo Total (R$)')
  return(tabelabairro)
}

conjdados.fun=function(dados){
  colnames(dados)=c('Endereço','Bairro','Área','Quartos', 'Garagem','Tipo de Imóvel',
                    'Aluguel (R$)','Custo Total (R$)')
  return(dados)
}

aluguelinfo.fun=function(dados,minmax){
  
  novosdados=dados[dados$rent>=minmax[1],] 
  novosdados=novosdados[novosdados$rent<=minmax[2],] 
  
  tabelaaluguel=data.frame('Área'=as.character(round(mean(novosdados[,3]),1)),
                          'Quartos'=as.character(round(mean(novosdados[,4]),1)),
                          'Garagem'=as.character(round(mean(novosdados[,5]),1)),
                          'Custo Total (R$)'=as.character(round(mean(novosdados[,8]),0)))
  colnames(tabelaaluguel)=c('Área','Quartos', 'Garagem','Custo Total (R$)')
  return(tabelaaluguel)
}

pizzaaluguel.fun=function(dados,minmax){
  novosdados1=dados[dados$rent>=minmax[1],] 
  novosdados1=novosdados1[novosdados1$rent<=minmax[2],] 
    
  dadosprop=data.frame(N=table(novosdados1$type),
                       prop=as.numeric(round(100*table(novosdados1$type)/sum(table(novosdados1$type)),2)))
  dadosprop$N.Var1=as.character(dadosprop$N.Var1)
  
  dadosprop = dadosprop %>%
    arrange(desc(N.Var1)) %>% 
    mutate(pos = cumsum(prop) - prop/2)
  
  dadosprop$nome=paste(dadosprop$N.Var1,'(',dadosprop$prop,'%)',sep='')

  return(dadosprop)
}

garageData = function(dados, number_district){
      dados_bairro <- dados[dados$district == name_district, ]
      dados_garagem <- ddply(dados_bairro[,-c(1,2,6)],.(garage),colwise(mean))
return(dados_garagem)
}

compararBairros = function(dados, bairros){
    bairros = bairros
  novosdados =dados %>%
    filter(district %in% bairros)
  tabelabairro=data.frame('Bairro'= bairros,
                          'Área'=as.character(round(mediaBairros(novosdados,novosdados[,3], bairros),1)),
                          'Quartos'=as.character(round(mediaBairros(novosdados,novosdados[,4], bairros),1)),
                          'Garagem'=as.character(round(mediaBairros(novosdados,novosdados[,5], bairros),1)),
                          'Aluguel (R$)'=as.character(round(mediaBairros(novosdados,novosdados[,7], bairros),0)),
                          'Custo Total (R$)'=as.character(round(mediaBairros(novosdados,novosdados[,8], bairros),0)))
  colnames(tabelabairro)=c('Bairro','Área','Quartos', 'Garagem','Aluguel (R$)','Custo Total (R$)')
  return(tabelabairro)
}
mediaBairros = function(data, coluna, bairros){
  n = length(bairros)
  medias = rep(NA, n)
  for (i in 1: n){
    medias[i] = mean(coluna[data$district == bairros[i]])
  }
  return(medias)
}

predBairros = function(data, bairros, valor){
  pred = data.frame(Bairros = bairros,
                  pred = rep(NA, length(bairros)))
  colnames(pred) = c("Bairros", "Aluguel (R$)")
  for (i in 1:length(bairros)){
    data = dados %>% 
      filter(district %in% bairros[i]) %>%
      select(rent, area)
    pred[i,2] = as.character(round(predict(lm(rent ~., data), data.frame(area = valor)),0))
  }
  return(pred)
}

pointBairros = function(data, bairros){
  data = dados %>% 
    filter(district %in% bairros)
  return(data)
}
```

Bairro
=======================================================================



Column {data-width=450}
-----------------------------------------------------------------------


### Informações do Bairro

```{r}
  selectInput("nome_bairro", "Bairro:", choices = sort(dados$district),selected=T)
  renderDataTable(datatable(bairroinfo.fun(dados,input$nome_bairro),
                            caption = paste('Média das informações do bairro',input$nome_bairro),
                            options = list(pageLength = 10,lengthChange=FALSE,dom = 'ltipr',bSort=F),
                            escape=F,rownames = F) %>%
    formatRound(c(1:3), 1) %>% 
    formatStyle(columns = c(1:5), 'text-align' = 'center'))
```

### `r renderText(paste('Tipo de imóvel no bairro',input$nome_bairro))`
```{r}
renderPlot({
  ggplot(pizza.fun(dados,input$nome_bairro), aes(x = "", y = prop, fill = N.Var1)) + 
    geom_bar(stat="identity",color=1) + 
    coord_polar(theta="y",start=0) + 
    scale_fill_brewer()+
    geom_label_repel(data = pizza.fun(dados,input$nome_bairro), aes(y = pos, label = nome),
                     size = 5.5, nudge_x=1, show.legend = FALSE) + 
    theme_void() +
    theme(legend.position="none")})

```



Column {data-width=550}
-----------------------------------------------------------------------


### Média das informações de todos os bairros

```{r}
renderDataTable(datatable(todosbairrosinfo.fun(dados)) %>%
      formatRound(c(2:6), 2) %>% 
      formatStyle(columns = c(2:6), 'text-align' = 'center'))
```


Aluguel
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------


### Informações do Aluguel

```{r}
  sliderInput('range','Escolha o intervalo do aluguel:',min=min(dados$rent),
              max=max(dados$rent), value=c(min(dados$rent),max(dados$rent)))

renderDataTable(datatable(aluguelinfo.fun(dados,c(input$range[1],input$range[2])),
                          caption = 'Média das informações do intervalo de aluguel',
                          options = list(pageLength = 10,lengthChange=FALSE,dom = 'ltipr',bSort=F),
                          escape=F,rownames = F) %>%
                  formatRound(c(1:3), 1) %>% 
                  formatStyle(columns = c(1:4), 'text-align' = 'center'))
```

### Valor do Aluguel por área do imóvel
```{r}
renderPlot({
    ggplot(dados, aes(x = area, y = rent)) +
      geom_point(colour = "skyblue") +
      labs(x = "Área", y = "Valor do aluguel (R$)") +
      geom_smooth(colour = "red")+
      theme_minimal(base_size = 12)+
    theme(legend.position="none")
  })
```



Column {data-width=500}
-----------------------------------------------------------------------


### Tipo de imóvel por intervalo de aluguel
```{r}

renderPlot({
  ggplot(pizzaaluguel.fun(dados,c(input$range[1],input$range[2])), aes(x = "", y = prop, fill = N.Var1)) + 
    geom_bar(stat="identity",color=1) + 
    coord_polar(theta="y",start=0) + 
    scale_fill_brewer()+
    geom_label_repel(data = pizzaaluguel.fun(dados,c(input$range[1],input$range[2])), aes(y = pos, label = nome),
                     size = 5.5, nudge_x=1, show.legend = FALSE) + 
    theme_void() +
    theme(legend.position="none")})

```


Comparação Entre Bairros
=======================================================================

Column {data-width=520}
-----------------------------------------------------------------------


 

```{r}
selectInput("nomes_bairros", "Bairros:", choices = sort(dados$district),
            selected=c('Aclimação','Jardim Vitória Régia'), multiple = TRUE)

renderDataTable(datatable(compararBairros(dados, input$nomes_bairros),
                          options = list(pageLength = 10,lengthChange=FALSE,dom ='ltr'),
                          escape=F,rownames = F,
                          caption='Média das variáveis dos bairros') %>%
      formatStyle(columns = c(2:6), 'text-align' = 'center'))
```



```{r}
div(style = "display: flex; align-items: center;",
      tags$label("Área:", style = "margin-right: 10px;"),
      sliderInput("area", "", min = 20, max = max(dados$area), value = 70)
  )
```


```{r}
renderDataTable(datatable(predBairros(dados, input$nomes_bairros, input$area),
                          options = list(pageLength = 10,lengthChange=FALSE,rownames = F,dom ='ltr',
                                         initComplete = JS("function(settings, json) {",
                                                           "$('th').css('text-align', 'center');",
                                                           "}")),
                          caption='Previsão do aluguel gasto por área e bairro') %>%
      formatStyle(columns = c(2), 'text-align' = 'center'))

```

Column {data-width=480}
-----------------------------------------------------------------------
### `r renderText(paste('Previsão do aluguel gasto por área e bairro'))`

```{r}
renderPlot({
    ggplot(pointBairros(dados, input$nomes_bairros), 
           aes(x = area, y = rent, group = district, 
                      colour = district)) +
      geom_point() +
      labs(x = "Área do imóvel", y = "Valor do aluguel (R$)", color = "Bairro:") +
      geom_smooth(method = "lm", se = FALSE)+
      theme_minimal(base_size = 13.5)
  })
```



Sobre
=======================================================================

Column {data-width=550}
-----------------------------------------------------------------------

### Descrição dos Dados

***

O conjunto de dados obtido encontra-se no Kaggle (https://www.kaggle.com/datasets/renatosn/sao-paulo-housing-prices), o qual fornece a seguinte descrição das variáveis:  

- Endereço: O endereço da propriedade;  
- Bairro: O bairro onde a propriedade está localizada;  
- Área: A área da propriedade em metros quadrados;  
- Quartos: O número de quartos na propriedade;  
- Garagem: O número de vagas de estacionamento disponíveis na propriedade;  
- Aluguel: O aluguel mensal da propriedade;  
- Tipo: O tipo da propriedade (apartamento, casa, etc.);  
- Total: O custo total da propriedade, incluindo aluguel, impostos e outras taxas.  

A partir do banco de dados original, foram feitas algumas mudanças no conjunto de dados utilizado para a elaboração deste aplicativo, onde houve correções de acentuação dos nomes dos bairros disponíveis. Além disso, o aplicativo foi desenvolvendo com o intuito de responder determinadas perguntas. Por isso, a seguir estão as perguntas e motodologia empregada para a resolução das mesmas:

- Quais são as características de um bairro específico?  
-- Na aba “Bairro”, podemos selecionar um bairro desejado e observar a média para cada variável presente.  

- Qual é a média de aluguel mensal nos diferentes bairros de São Paulo?  
-- Observa-se a média de aluguel mensal por bairro nas informações do bairro da aba “Bairro”.  

- Quais são os tipos de imóveis mais comuns em cada bairro?  
-- No gráfico de setores da aba “Bairro”, há a composição por tipo de imóvel de cada bairro.  

- Qual é a correlação entre o tamanho do imóvel e o valor do aluguel?  
-- Na aba “Aluguel”, analisa-se a correlação entre tamanho do imóvel e o valor do aluguel através de um gráfico de dispersão.  

- Quais são os bairros mais acessíveis e mais caros de São Paulo?  
-- Na tabela “média das informações de todos os bairros” da aba “Bairro”, podemos observar os bairros mais caros e mais acessíveis, ordenando em crescente e decrescente o valor do Aluguel ou o Custo Total. Podemos fazer o mesmo para as demais variáveis.  

- Determinado bairro é melhor que outro?  
-- Nas informações dos bairros na aba “Comparação entre Bairros”, pode-se filtrar os bairros desejados e encontrar o preferível com base nas variáveis presentes, de modo a visualizar suas respectivas informações de maneira conjunta.   

- Quais são as características esperadas de um imóvel com base no aluguel?  
-- Na aba “Aluguel”, há as médias das demais variáveis a partir de um intervalo de valores do Aluguel.  

- Qual a previsão do valor de Aluguel em cada bairro?  
-- Na aba “Comparação entre Bairros”, há a previsão do aluguel em cada bairro selecionado com base na Área do imóvel.


Observação: o código está disponível clicando em “Source Code” no canto superior direito.

Column {data-width=450}
-----------------------------------------------------------------------
### Conjunto de Dados (Download)
```{r}
renderDataTable(datatable(conjdados.fun(dados),extensions = 'Buttons',
                          options = list(lengthMenu=c(11657,3,60),dom='Bfrtip',buttons=c('csv'))) %>%
      formatStyle(columns = c(1:8), 'text-align' = 'center'))

```





